# Generated by Django 6.0.2 on 2026-03-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ProjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('class_index', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.project')),
            ],
            options={
                'ordering': ['class_index'],
                'unique_together': {('project', 'class_index'), ('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='project_images/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'original_name')},
            },
        ),
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(blank=True, max_length=120)),
                ('object_index', models.PositiveIntegerField(default=1)),
                ('x_min', models.FloatField()),
                ('y_min', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='main.projectclass')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='main.projectimage')),
            ],
            options={
                'ordering': ['object_index', 'id'],
            },
        ),
    ]
